### ISSUE TITLE
[Bug]: Creepers have default player ticking damage sound.

### ISSUE THREAD

**Issue by pantsguyapp** [Joo5h/Creeper-Overhaul#18]
### Bug Description

When a creeper is damaged or when it died, only default player hurt sounds will play

### How to Reproduce?

Hit a mod's creeper

### Expected Behavior

The creepers sounds will play instead

### Version

0.3.0

### Mod Loader Version

1.18.1

### Mod Loader

Forge

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
This will be done in 1.19.
