### ISSUE TITLE
Kitty Slippers from Artifacts mod doesn't work vs Creeper Overhaul creepers

### ISSUE THREAD

**Issue by Lavan** [Joo5h/Creeper-Overhaul#2]
The Kitty Slippers from Artifacts acts as if the player has a cat nearby (ie creepers are afraid of them) when worn. The creepers from Creeper Overhaul ignores them which makes them useless (no "normal" creepers) if you have both mods installed (as they are in the ATM7 modpack). 

Forge: 39.0.10
Creeper Overhaul: 0.2.0
Artifacts: 4.0.2
Java: 17.0.1

**Comment by Bronski** [comment]
I was also going to say this. I'm glad I looked first. :D

**Comment by SteelChikorita** [comment]
Can confirm this still happens in the latest version, would love to see this fixed in a future update :)

**Comment by ThatGravyBoat** [comment]
This will be fixed in the 1.19 version but wont be in 1.18 due how the 1.18 version was coded and it would require direct compact with the mod which is not optimal.
