### ISSUE TITLE
[Bug]: Not sure if bug or feature, Missing config?

### ISSUE THREAD

**Issue by Ashley123477** [Joo5h/Creeper-Overhaul#22]
### Bug Description

Doesnt have a config file

### Expected Behavior

Config file to be produced

### Version

1.3.0-fabric.jar

### Mod Loader Version

Fabric 0.13.3

### Mod Loader

Fabric

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by TwoPointInfinity** [comment]
i 2nd this.

**Comment by ThatGravyBoat** [comment]
I did not put the config on fabric because I did not want to write a config system. in 1.19 I changed it so both forge and fabric have configs.
