### ISSUE TITLE
[Bug]: Wolfs attack modded creepers, wolves do not attack vanilla creeper.

### ISSUE THREAD

**Issue by TwoPointInfinity** [Joo5h/Creeper-Overhaul#24]
### Bug Description

Pet dogs attack creepers when they shouldnt. they instantly die and make a mess. 

### How to Reproduce?

find wolf
tame it
shoot a creeper
dog attacks creeper
dog dies
hole in earth

### Expected Behavior

dog does not attack creeper when you engage creeper in combat, nor does it waste time looking for the enemy that hit you when it explodes.

### Version

1.3.1

### Mod Loader Version

0.10.2-0.14.5

### Mod Loader

Fabric

### Acknowledgement

- [X] I agree that I have read what was said above this check box.

**Comment by ThatGravyBoat** [comment]
This will be fixed in the 1.19 version but wont be in 1.18 due how the 1.18 version was coded.
