### ISSUE TITLE
[Feature Request]: Add a config option to disable creeper block damage

### ISSUE THREAD

**Issue by Mp5cz** [Joo5h/Creeper-Overhaul#4]
### Solution(s)

I would greatly appreciate if there was a config option that would prevent creepers from this mod from destroying blocks. 
It would probably best if each creeper type could be configured separately, but a single, global setting will work fine for my purposes.

### Mod Version

0.2.0

### Mod Loader Version

1.18.1 - 39.0.14

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
There is a thing in vanilla for that its called the mob griefing gamerule.

**Comment by Mp5cz** [comment]
I'm aware of that, but that also disables Wither and Ender Dragon block damage, Villager crop harvesting etc. I would like to have the option to disable creeper griefing while keeping the other features.

**Comment by brandonvdongen** [comment]
+1 on this. I was actually here to request the same thing only to find this. 

as it stands MobGriefing turns off WAY too much. even piglin trading, which is a essential mechanic in the modpack we're playing right now. having a way to disable JUST creepers would be a godsend.

**Comment by Mp5cz** [comment]
For anyone with this same problem, I just found a forge mod called "More Mobgriefing Options" that more or less solves this. That said, it would be optimal if this was a native feature.
